version: '2.2'

services:
  dancedb:
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    image: mysql
    ports:
    - "2014:3306"
    restart: always
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=dancechampionship
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  dancerest:
    image: dancetest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8087:8080
    links:
      - dancedb
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=user123 --execute \"SHOW DATABASES;\"
      timeout: 50s1
      retries: 15
      interval: 20s